name: vscode-aeon build

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            artifact: build-Linux release
          # - name: macOS
          #   os: macos-latest
          #   artifact: build-macOS
          - name: Windows
            os: windows-latest
            artifact: build-Windows
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
        if: matrix.os == 'windows-latest'

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Package
        run: npm run package #--workspace=aeon
        if: ${{ !startsWith(github.ref, 'refs/tags/v') || !endsWith(github.ref, '-pre') }}

      - name: Package pre-release
        run: npm run packagePreRelease #--workspace=aeon
        if: ${{ startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-pre') }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: vscode-aeon
          path: 'vscode-aeon/aeon-*.vsix'

      - name: Publish packaged extension
        if: ${{ startsWith(github.ref, 'refs/tags/v') && !endsWith(github.ref, '-pre') && matrix.os == 'ubuntu-latest' }}
        run: |
          cd vscode-aeon
          npx @vscode/vsce publish -i aeon-*.vsix
          npx ovsx publish aeon-*.vsix
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish packaged pre-release extension
        if: ${{ startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-pre') && matrix.os == 'ubuntu-latest' }}
        run: |
          cd vscode-aeon
          npx @vscode/vsce publish --pre-release -i aeon-*.vsix
          npx ovsx publish --pre-release aeon-*.vsix
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Upload extension as release
        if: startsWith(github.ref, 'refs/tags/v') && matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: 'vscode-aeon/aeon-*.vsix'
          fail_on_unmatched_files: true
          prerelease: ${{ endsWith(github.ref, '-pre') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: npm run lint


    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
